### ISSUE TITLE
generic script plugin

### ISSUE THREAD

**Issue by muzzol** [z-eos/regather#5]
this is a feature request for a generic script plugin.

I'm was trying to test this consumer but I don't have de knowledge to create a plugin from scratch, so it would be nice to have an external hook to run on every change.
something like

```
[service script test1]
  plugin      = script
  uid              = testuser1
  gid              = testgroup1
  ns_keyfile  = /opt/test1.sh
  params      = dn,uid,gecos


```

thanks for your time.

**Comment by z-eos** [comment]
check bc38b35..5f1a61f please

**Comment by muzzol** [comment]
wow! that was really fast :)

if I understand properly that creates a file, but I would like to execute a script with some parameters.

in my example I just copy pasted from one of your examples and ns_keyfile should be something like:


    run_script   = /opt/test1.sh
    
does that makes sense to you?

**Comment by z-eos** [comment]
Could you be a bit more specific on how do you see that?
What and how should be passed to the script?

**Comment by muzzol** [comment]
> Could you be a bit more specific on how do you see that?
> What and how should be passed to the script?

sure, let me explain an example. I execute some scripts depending on user groups, so if a user is added to a group called **Support** I run some tasks like creating some dirs and copying some files.

so in this example I should monitorize **memberOf** and if that is changed I should pass that to the script and then the script do its job.

instead of parameters, you could expose some variable, like for example **FULL_LDIF** and that is evaluated inside the script.

**Comment by z-eos** [comment]
check v0.81.00 please

**Comment by muzzol** [comment]
I didn't have time to test it yet but it looks really promising :)

I see all environment variables you use:


```
  $ENV{REGATHER_LDAP_OBJ_DN}             = $self->obj->dn;
  $ENV{REGATHER_LDAP_OBJ_LDIF}           = $self->obj->ldif;
  $ENV{REGATHER_LDAP_SYNC_CONTROL_CODE}  = $self->syncstate;
  $ENV{REGATHER_LDAP_SYNC_CONTROL_NAME}  = SYNST->[$self->syncstate];
  foreach my $k ($self->obj->attributes) {
    $ENV{"REGATHER_LDAP_OBJ_ATTR_" . $k} = $self->obj->get_value($k);
 
```

that's exactly what I needed.

I think you can close this ticket now and if I find any problem I'll open another one.

thanks a lot for your time!!
